### ISSUE TITLE
Different cohens d for t.test and t_test

### ISSUE THREAD

**Issue by stefanleach** [dgromer/apa#11]
Hi there,

Just a quick query/comment. I seem to be getting different effect size estimates when piping the results of a t.test vs. t_test to the apa() function. This is happening with an independent samples test and when requesting Cohens d. 

For example, I receive one estimate for Cohens d when running a script equivalent to the following, with the "t_test" function:

```
data %>%
  summarize(result = t_test(x, y, paired = FALSE, var.equal = TRUE) %>% apa(es = "cohens_d"))
```
...but a different estimate for Cohens d when running a script equivalent to the following, , with the "t.test" function:
```
data %>%
  summarize(result = t.test(x, y, paired = FALSE, var.equal = TRUE) %>% apa(es = "cohens_d"))
```

Any input would be helpful.

Cheers,

Stefan

**Comment by stefanleach** [comment]
Doing a few more tests on this, I can't seem to replicate this issue. The following code produces the same Cohens d estimates for seed 1-10.

```
library(tidyverse)
library(apa)

set.seed(6)

test <- 
  data.frame(x = rnorm(50),
             y = rnorm(50))

test %>%
  summarize(result = t_test(x, y, paired = FALSE, var.equal = TRUE) %>% apa(es = "cohens_d"))

test %>%
  summarize(result = t.test(x, y, paired = FALSE, var.equal = TRUE) %>% apa(es = "cohens_d"))
```

**Comment by dgromer** [comment]
If you pass the result of `t_test` to `cohens_d` (via `apa`), Cohen's d is calculated from the raw data via the following formula:

<img src="https://render.githubusercontent.com/render/math?math=%24d%3D%5Cfrac%7B%5Coverline%7BX%7D_1%2B%5Coverline%7BX%7D_2%7D%7B%5Csqrt%7B%5Cfrac%7B(n_1-1)SD%5E2_1%2B(n_2-1)SD%5E2_2%7D%7Bn_1%2Bn_2-2%7D%7D%7D%24">

If you pass the result of `t.test`, `cohens_d` can't calculate Cohens'd from the raw data, because the data is not included in the list returned by `t.test`. For this reason, `cohens_d` uses the following formula:

<img src="https://render.githubusercontent.com/render/math?math=%24d%20%5Capprox%202%20%5Ctimes%20t%2F%5Csqrt%7BN%7D%24">

(both formulas from [Lakens, 2013](https://www.frontiersin.org/articles/10.3389/fpsyg.2013.00863/full))

If your sample sizes are not equal, then the two formulas might not produce the same results.

**Comment by stefanleach** [comment]
Ah, that makes sense. Good to know! 👍 

Thanks for the speedy response!
